# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import numpy as np
import cv2
import dataplot


class Ui_Form(object):
    def setupUi(self, Form):
        self.obs = np.zeros(7)
        self.index = 0
        Form.setObjectName("Form")
        Form.resize(1200, 1000)
        Form.setMinimumSize(QtCore.QSize(1200, 1000))
        Form.setMaximumSize(QtCore.QSize(1200, 1000))
        self.mitrixshow = QtWidgets.QLabel(Form)
        self.mitrixshow.setGeometry(QtCore.QRect(750, 50, 400, 400))
        self.mitrixshow.setMouseTracking(True)
        self.mitrixshow.setFrameShape(QtWidgets.QFrame.Box)
        self.mitrixshow.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.mitrixshow.setText("")
        self.mitrixshow.setObjectName("mitrixshow")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 330, 600, 120))
        self.label_2.setMouseTracking(True)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(60, 60, 660, 51))
        self.label_3.setMinimumSize(QtCore.QSize(541, 51))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(90, 160, 281, 51))
        self.label_4.setLineWidth(1)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(400, 160, 281, 51))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(100, 225, 151, 51))
        self.label_6.setLineWidth(1)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(310, 225, 171, 51))
        self.label_7.setLineWidth(1)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(500, 225, 151, 51))
        self.label_8.setLineWidth(1)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setWordWrap(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(230, 360, 151, 60))
        self.label_9.setLineWidth(1)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(False)
        self.label_9.setObjectName("label_9")
        self.correct = QtWidgets.QLabel(Form)
        self.correct.setGeometry(QtCore.QRect(420, 360, 171, 60))
        self.correct.setLineWidth(1)
        self.correct.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.correct.setWordWrap(False)
        self.correct.setObjectName("correct")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(750, 450, 400, 51))
        self.label_10.setLineWidth(1)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(550, 540, 120, 50))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.selectionchange)

        self.signshow_real = QtWidgets.QLabel(Form)
        self.signshow_real.setGeometry(QtCore.QRect(70, 640, 600, 150))
        self.signshow_real.setMouseTracking(True)
        self.signshow_real.setFrameShape(QtWidgets.QFrame.Box)
        self.signshow_real.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.signshow_real.setText("")
        self.signshow_real.setObjectName("signshow_real")
        self.signshow_vir = QtWidgets.QLabel(Form)
        self.signshow_vir.setGeometry(QtCore.QRect(70, 790, 600, 150))
        self.signshow_vir.setMouseTracking(True)
        self.signshow_vir.setFrameShape(QtWidgets.QFrame.Box)
        self.signshow_vir.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.signshow_vir.setText("")
        self.signshow_vir.setObjectName("signshow_vir")
        self.stars_show = QtWidgets.QLabel(Form)
        self.stars_show.setGeometry(QtCore.QRect(750, 540, 400, 400))
        self.stars_show.setMouseTracking(True)
        self.stars_show.setFrameShape(QtWidgets.QFrame.Box)
        self.stars_show.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.stars_show.setText("")
        self.stars_show.setObjectName("stars_show")
        # self.label_11 = QtWidgets.QLabel(Form)
        # self.label_11.setGeometry(QtCore.QRect(550, 540, 120, 50))
        # self.label_11.setLineWidth(1)
        # self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_11.setWordWrap(False)
        # self.label_11.setObjectName("label_11")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(70, 540, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.currentIndexChanged.connect(self.selectionchange)
        self.signshow_real_2 = QtWidgets.QLabel(Form)
        self.signshow_real_2.setGeometry(QtCore.QRect(400, 540, 120, 50))
        self.signshow_real_2.setMouseTracking(True)
        self.signshow_real_2.setFrameShape(QtWidgets.QFrame.Box)
        self.signshow_real_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.signshow_real_2.setText("")
        self.signshow_real_2.setObjectName("signshow_real_2")
        self.signshow_real_3 = QtWidgets.QLabel(Form)
        self.signshow_real_3.setGeometry(QtCore.QRect(250, 540, 120, 50))
        self.signshow_real_3.setMouseTracking(True)
        self.signshow_real_3.setFrameShape(QtWidgets.QFrame.Box)
        self.signshow_real_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.signshow_real_3.setText("")
        self.signshow_real_3.setObjectName("signshow_real_3")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(70, 490, 150, 50))
        self.label_12.setLineWidth(1)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(250, 490, 120, 50))
        self.label_13.setLineWidth(1)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(400, 490, 120, 50))
        self.label_14.setLineWidth(1)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(False)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(750, 940, 400, 51))
        self.label_15.setLineWidth(1)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setWordWrap(False)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(69, 610, 600, 40))
        self.label_16.setLineWidth(1)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setWordWrap(False)
        self.label_16.setObjectName("label_16")

        self.radioButton_reinforcement = QtWidgets.QRadioButton(Form)
        self.radioButton_reinforcement.setGeometry(QtCore.QRect(80, 240, 16, 16))
        self.radioButton_reinforcement.setText("1")
        self.radioButton_reinforcement.setObjectName("radioButton_reinforcement")
        self.radioButton_reinforcement.toggled.connect(lambda: self.radiobuttonstate(self.radioButton_reinforcement))
        self.radioButton_reinforcement.setChecked(True)

        self.radioButton_all = QtWidgets.QRadioButton(Form)
        self.radioButton_all.setGeometry(QtCore.QRect(290, 240, 16, 16))
        self.radioButton_all.setText("2")
        self.radioButton_all.setObjectName("radioButton_all")
        self.radioButton_all.toggled.connect(lambda: self.radiobuttonstate(self.radioButton_all))

        self.radioButton_origin = QtWidgets.QRadioButton(Form)
        self.radioButton_origin.setGeometry(QtCore.QRect(490, 240, 16, 16))
        self.radioButton_origin.setText("3")
        self.radioButton_origin.setObjectName("radioButton_origin")
        self.radioButton_origin.toggled.connect(lambda: self.radiobuttonstate(self.radioButton_origin))

        self.selectionchange()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:20pt;\"><b>基于强化学习和星座图时频特征的调制识别结果展示</b></span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">所选数据集：RadioML2016.04c</span></p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">所选信噪比：6dB</span></p><p><br/></p><p><br/></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">强化学习筛选数据</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">全部时频通道数据</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">原始星座图数据</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">平均识别准确率：</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">信号调制识别结果的混淆矩阵图示</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "下一条数据"))
        self.comboBox.setItemText(0, _translate("Form", "随机数据"))
        self.comboBox.setItemText(1, _translate("Form", "GFSK"))
        self.comboBox.setItemText(2, _translate("Form", "WBFM"))
        self.comboBox.setItemText(3, _translate("Form", "AM-SSB"))
        self.comboBox.setItemText(4, _translate("Form", "AM-DSB"))
        self.comboBox.setItemText(5, _translate("Form", "QPSK"))
        self.comboBox.setItemText(6, _translate("Form", "QAM16"))
        self.comboBox.setItemText(7, _translate("Form", "CPFSK"))
        self.comboBox.setItemText(8, _translate("Form", "BPSK"))
        self.comboBox.setItemText(9, _translate("Form", "PAM4"))
        self.comboBox.setItemText(10, _translate("Form", "QAM64"))
        self.comboBox.setItemText(11, _translate("Form", "8PSK"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">数据类型</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">调制类别</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt;\">识别类别</span></p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">信号时频分解特征通道图示</span></p></body></html>"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">信号时域波形图</span></p><p><br/></p></body></html>"))

    def radiobuttonstate(self,button):
        _translate = QtCore.QCoreApplication.translate
        if button.text() == "3":
            if button.isChecked():
                path = './img/origin.png'
                self.mitrixshow.setPixmap(QtGui.QPixmap(path))
                self.mitrixshow.setScaledContents(True)
                self.correct.setText(_translate("Form", "<html><head/><body><p><br/><span style=\" font-size:18pt;\">94.36%</span></p><p><br/></p></body></html>"))
                self.obs = np.zeros(7)
                self.obs[0] = 1
        elif button.text() == "2":
            if button.isChecked():
                path = './img/all.png'
                self.mitrixshow.setPixmap(QtGui.QPixmap(path))
                self.mitrixshow.setScaledContents(True)
                self.correct.setText(_translate("Form", "<html><head/><body><p><br/><span style=\" font-size:18pt;\">95.59%</span></p><p><br/></p></body></html>"))
                self.obs = np.ones(7)
        else:
            if button.isChecked():
                path = './img/reinforcement.png'
                self.mitrixshow.setPixmap(QtGui.QPixmap(path))
                self.mitrixshow.setScaledContents(True)
                self.correct.setText(_translate("Form", "<html><head/><body><p><br/><span style=\" font-size:18pt;\">96.41%</span></p><p><br/></p></body></html>"))
                self.obs = np.zeros(7)
                self.obs[0],self.obs[4], self.obs[5] = 1, 1, 1


    def selectionchange(self,):
        _translate = QtCore.QCoreApplication.translate
        comboBoxName = self.comboBox.currentText()
        label1,label2 = dataplot.dataharr(comboBoxName, self.obs)
        self.signshow_real_3.setText(_translate("Form", "<html><head/><body><p><br/><span style=\" font-size:18pt;\">"+label1+"</span></p><p><br/></p></body></html>"))
        self.signshow_real_2.setText(_translate("Form", "<html><head/><body><p><br/><span style=\" font-size:18pt;\">"+label2+"</span></p><p><br/></p></body></html>"))
        self.stars_show.setPixmap(QtGui.QPixmap('./img/star.png'))
        self.stars_show.setScaledContents(True)
        self.signshow_real.setPixmap(QtGui.QPixmap('./img/real.png'))
        self.signshow_real.setScaledContents(True)
        self.signshow_vir.setPixmap(QtGui.QPixmap('./img/virtual.png'))
        self.signshow_vir.setScaledContents(True)


class MyWindow(QtWidgets.QMainWindow, Ui_Form):
    def __init__(self):
        super(MyWindow, self).__init__()  

        self.setupUi(self)
        self.setWindowTitle('强化学习可视化展示界面')


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    w = MyWindow()
    w.show()
    sys.exit(app.exec_())